import { IcsEvent } from "ts-ics";

export function createIcsEvent(
  summary: string,
  start: Date,
  end: Date
): IcsEvent {
  const now = new Date();
  return {
    uid: `aion-${now.getTime()}`,
    summary,
    start: { date: start },
    end: { date: end },
    stamp: { date: now },
    description: `Generated by AION`,
    status: "CONFIRMED",
    categories: ["AION"],
    location: "Generated by AION Interpreter",
    url: "https://example.com",
    organizer: {
      name: "Aion System",
      email: "noreply@example.com",
    },
  };
}
